export const categories = [
    { id: 1, title: "Home", subcategories: ["Top News", "Berita Utama", "Videos", "Opinion", "World", "Lifestyle", "Business", "Sports"] },
    { id: 2, title: "News", subcategories: ["Malaysia", "Borneo+", "South East Asia", "World"] },
    { id: 3, title: "Berita", subcategories: ["Tempatan", "Pandangan", "Dunia"] },
    { id: 4, title: "Opinion", subcategories: ["Column", "Editorial", "Letters"] },
    { id: 5, title: "World", subcategories: [] },
    { id: 6, title: "Business", subcategories: ["Local Business", "World Business"] },
    { id: 7, title: "Property", subcategories: [] },
    { id: 8, title: "Sports", subcategories: ["Football", "Badminton", "MotorSports", "Tennis"] },
    { id: 9, title: "Lifestyle", subcategories: ["Simple Stories", "Travel", "Food", "Entertainment", "Money", "Health & Family", "Pets", "Automotive"] },
    { id: 10, title: "Videos", subcategories: ["Fmt Lifestyle", "Fmt Exclusive", "Fmt News Capsule"] },
  ];

  export const categoryMapping: Record<string, string> = {
    VIDEOS: 'fmt-news',
    MALAYSIA: 'malaysia',
    OPINION: 'all-opinion',
    WORLD: 'all-world',
    'TOP WORLD': 'world',
    BUSINESS: 'business',
    'TOP BUSINESS': 'business',
    'TOP SPORTS': 'sports',
    "SUPER BM": "berita",
    'TOP BM' : 'berita',
    'TOP-BM' : 'berita',
    SPORTS: 'all-sports',
    LIFESTYLE: 'all-lifestyle',
    'BERITA UTAMA': 'berita',
    'BERITA': 'all-berita',
    'TOP NEWS': 'top-news',
    'TOP LIFESTYE': 'lifestyle',
    'TOP OPINION': 'opinion',
    HOME: 'headlines',
    NEWS: 'top-news',
    COLUMN: 'column',
    EDITORIAL: 'editorial',
    LETTERS: 'letter',
    'LOCAL BUSINESS': 'local-business',
    'WORLD BUSINESS': 'world-business',
    FOOTBALL: 'football',
    BADMINTON: 'badminton',
    MOTORSPORTS: 'motorsports',
    TENNIS: 'tennis',
    PROPERTY: 'property',
    TRAVEL: 'travel',
    AUTOMOTIVE: 'automotive',
    FOOD: 'food',
    HEALTH: 'health',
    ENTERTAINMENT: 'entertainment',
    MONEY: 'money',
    PETS: 'pets',
    'SIMPLE STORIES': 'simple-stories',
    'BORNEO+': 'borneo+',
    'SOUTH EAST ASIA': 'south-east-asia',
    TEMPATAN: 'tempatan',
    DUNIA: 'dunia',
    PANDANGAN: 'pandangan',
    VIDEO: 'videos',
    'FMT NEWS': 'fmt-news',
    'FMT LIFESTYLE': 'fmt-lifestyle',
    'FMT EXCLUSIVE': 'fmt-exclusive',
    'FMT NEWS CAPSULE': 'fmt-news-capsule',
    'SUPER HIGHLIGHT': 'super-highlight',
    'HEALTH & FAMILY': 'health',
  };


  export const categoryMapping1: Record<string, string> = {
    VIDEOS: 'fmt-news',
    MALAYSIA: 'malaysia',
    OPINION: 'opinion',
    WORLD: 'world',
    'TOP WORLD': 'world',
    BUSINESS: 'business',
    'TOP BUSINESS': 'business',
    'TOP SPORTS': 'sports',
    "SUPER BM": "berita",
    'TOP BM' : 'berita',
    'TOP-BM' : 'berita',
    SPORTS: 'sports',
    LIFESTYLE: 'lifestyle',
    'BERITA UTAMA': 'berita',
    'BERITA': 'all-berita',
    'TOP NEWS': 'top-news',
    'TOP LIFESTYE': 'lifestyle',
    'TOP OPINION': 'opinion',
    HOME: 'headlines',
    NEWS: 'top-news',
    COLUMN: 'column',
    EDITORIAL: 'editorial',
    LETTERS: 'letter',
    'LOCAL BUSINESS': 'local-business',
    'WORLD BUSINESS': 'world-business',
    FOOTBALL: 'football',
    BADMINTON: 'badminton',
    MOTORSPORTS: 'motorsports',
    TENNIS: 'tennis',
    PROPERTY: 'property',
    TRAVEL: 'travel',
    AUTOMOTIVE: 'automotive',
    FOOD: 'food',
    HEALTH: 'health',
    ENTERTAINMENT: 'entertainment',
    MONEY: 'money',
    PETS: 'pets',
    'SIMPLE STORIES': 'simple-stories',
    'BORNEO+': 'borneo+',
    'SOUTH EAST ASIA': 'south-east-asia',
    TEMPATAN: 'tempatan',
    DUNIA: 'dunia',
    PANDANGAN: 'pandangan',
    VIDEO: 'videos',
    'FMT NEWS': 'fmt-news',
    'FMT LIFESTYLE': 'fmt-lifestyle',
    'FMT EXCLUSIVE': 'fmt-exclusive',
    'FMT NEWS CAPSULE': 'fmt-news-capsule',
    'SUPER HIGHLIGHT': 'super-highlight',
    'HEALTH & FAMILY': 'health',
  };